# <center>Brain Stroke Accuracy Check</center>

In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [11]:
dt = pd.read_csv("stroke_risk_dataset.csv")
dt

Chest Pain  Shortness of Breath  Irregular Heartbeat  \
0               0                    1                    1   
1               0                    0                    1   
2               1                    0                    0   
3               1                    0                    1   
4               0                    0                    1   
...           ...                  ...                  ...   
69995           1                    0                    0   
69996           0                    0                    0   
69997           1                    1                    0   
69998           0                    1                    1   
69999           0                    1                    0   

       Fatigue & Weakness  Dizziness  Swelling (Edema)  \
0                       1          0                 0   
1                       0          0                 1   
2                       1          1                 1   
3                       1          0                 1   
4                       0          0                 1   
...                   ...        ...               ...   
69995                   0          0                 0   
69996                   1          0                 1   
69997                   1          1                 1   
69998                   1          1                 0   
69999                   0          0                 0   

       Pain in Neck/Jaw/Shoulder/Back  Excessive Sweating  Persistent Cough  \
0                                   0                   1                 1   
1                                   0                   0                 0   
2                                   0                   0                 1   
3                                   1                   1                 1   
4                                   0                   1                 0   
...                               ...                 ...               ...   
69995                               0                   1                 0   
69996                               0                   1                 0   
69997                               0                   0                 0   
69998                               0                   0                 0   
69999                               0                   1                 1   

       Nausea/Vomiting  High Blood Pressure  Chest Discomfort (Activity)  \
0                    1                    0                            1   
1                    0                    1                            0   
2                    0                    0                            0   
3                    1                    1                            0   
4                    1                    1                            0   
...                ...                  ...                          ...   
69995                1                    1                            1   
69996                0                    0                            1   
69997                0                    1                            0   
69998                0                    0                            1   
69999                1                    1                            1   

       Cold Hands/Feet  Snoring/Sleep Apnea  Anxiety/Feeling of Doom  Age  \
0                    1                    0                        0   54   
1                    1                    1                        0   49   
2                    0                    1                        0   62   
3                    0                    0                        0   48   
4                    0                    1                        1   61   
...                ...                  ...                      ...  ...   
69995                0                    0                        1   18   
69996                1                    1                        0   24  

In [12]:
x = dt.iloc[:,0:17]
y = dt.iloc[:,17:]

In [13]:
X_train,X_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=0.3)

In [14]:
X_train

Chest Pain  Shortness of Breath  Irregular Heartbeat  \
59982           0                    1                    0   
13048           0                    1                    1   
13206           1                    0                    0   
25113           0                    0                    0   
15311           1                    1                    1   
...           ...                  ...                  ...   
21243           0                    0                    0   
45891           1                    1                    1   
42613           1                    0                    1   
43567           0                    1                    0   
68268           1                    1                    1   

       Fatigue & Weakness  Dizziness  Swelling (Edema)  \
59982                   0          0                 1   
13048                   1          0                 0   
13206                   0          1                 0   
25113                   0          0                 0   
15311                   0          1                 0   
...                   ...        ...               ...   
21243                   1          1                 0   
45891                   0          1                 1   
42613                   0          1                 1   
43567                   0          0                 0   
68268                   0          0                 1   

       Pain in Neck/Jaw/Shoulder/Back  Excessive Sweating  Persistent Cough  \
59982                               0                   0                 1   
13048                               0                   1                 1   
13206                               0                   0                 0   
25113                               0                   1                 1   
15311                               1                   0                 0   
...                               ...                 ...               ...   
21243                               1                   1                 0   
45891                               0                   1                 1   
42613                               1                   0                 1   
43567                               0                   0                 0   
68268                               1                   0                 0   

       Nausea/Vomiting  High Blood Pressure  Chest Discomfort (Activity)  \
59982                1                    0                            1   
13048                1                    0                            0   
13206                0                    1                            1   
25113                0                    1                            1   
15311                0                    1                            0   
...                ...                  ...                          ...   
21243                0                    1                            0   
45891                1                    0                            1   
42613                1                    0                            1   
43567                1                    0                            1   
68268                0                    1                            1   

       Cold Hands/Feet  Snoring/Sleep Apnea  Anxiety/Feeling of Doom  Age  \
59982                1                    1                        1   78   
13048                1                    1                        0   52   
13206                1                    1                        0   29   
25113                0                    1                        0   89   
15311                1                    1                        1   34   
...                ...                  ...                      ...  ...   
21243                0                    0                        1   31   
45891                1                    0                        1   67  

In [15]:
X_test

Chest Pain  Shortness of Breath  Irregular Heartbeat  \
10840           0                    1                    1   
56267           1                    0                    1   
14849           1                    1                    1   
62726           1                    0                    1   
47180           0                    0                    0   
...           ...                  ...                  ...   
30500           1                    0                    1   
27609           1                    1                    0   
6155            0                    0                    1   
64241           1                    1                    0   
23910           0                    0                    1   

       Fatigue & Weakness  Dizziness  Swelling (Edema)  \
10840                   0          1                 1   
56267                   0          0                 1   
14849                   1          0                 1   
62726                   1          1                 0   
47180                   0          0                 0   
...                   ...        ...               ...   
30500                   0          1                 0   
27609                   1          0                 0   
6155                    0          1                 0   
64241                   1          0                 0   
23910                   1          0                 1   

       Pain in Neck/Jaw/Shoulder/Back  Excessive Sweating  Persistent Cough  \
10840                               0                   1                 0   
56267                               1                   1                 0   
14849                               0                   1                 0   
62726                               0                   0                 1   
47180                               0                   0                 0   
...                               ...                 ...               ...   
30500                               0                   0                 0   
27609                               0                   1                 1   
6155                                1                   0                 1   
64241                               1                   0                 0   
23910                               0                   1                 1   

       Nausea/Vomiting  High Blood Pressure  Chest Discomfort (Activity)  \
10840                0                    1                            1   
56267                1                    1                            1   
14849                1                    1                            0   
62726                1                    1                            1   
47180                0                    1                            0   
...                ...                  ...                          ...   
30500                1                    1                            1   
27609                1                    0                            0   
6155                 1                    1                            0   
64241                1                    1                            0   
23910                0                    0                            0   

       Cold Hands/Feet  Snoring/Sleep Apnea  Anxiety/Feeling of Doom  Age  \
10840                0                    0                        1   85   
56267                0                    1                        1   66   
14849                0                    1                        1   41   
62726                1                    0                        0   32   
47180                1                    0                        0   43   
...                ...                  ...                      ...  ...   
30500                1                    1                        1   74   
27609                1                    0                        1   27  

In [16]:
y_train

At Risk (Binary)
59982                 1
13048                 1
13206                 0
25113                 1
15311                 1
...                 ...
21243                 0
45891                 1
42613                 1
43567                 0
68268                 1

[49000 rows x 1 columns]

In [17]:
y_test

At Risk (Binary)
10840                 1
56267                 1
14849                 1
62726                 1
47180                 0
...                 ...
30500                 1
27609                 0
6155                  1
64241                 0
23910                 1

[21000 rows x 1 columns]

In [18]:
sc = StandardScaler()

In [19]:
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.fit_transform(X_test)

In [20]:
X_train_std

array([[-1.0020838 ,  1.00519718, -0.99816495, ...,  1.0038851 ,
         1.13622745,  1.01027232],
       [-1.0020838 ,  1.00519718,  1.00183842, ..., -0.99612994,
        -0.09715869,  0.10106349],
       [ 0.99792053, -0.99482969, -0.99816495, ..., -0.99612994,
        -1.18823104, -1.40262805],
       ...,
       [ 0.99792053, -0.99482969,  1.00183842, ..., -0.99612994,
        -0.2869104 ,  0.31088091],
       [-1.0020838 ,  1.00519718, -0.99816495, ...,  1.0038851 ,
        -0.19203454, -1.36765848],
       [ 0.99792053,  1.00519718,  1.00183842, ..., -0.99612994,
         1.04135159,  0.59063748]])

In [21]:
X_test_std

array([[-1.00764829,  1.01149463,  1.00314781, ...,  0.99184279,
         1.46901679,  1.25340118],
       [ 0.99240976, -0.98863599,  1.00314781, ...,  0.99184279,
         0.56644445,  1.28834916],
       [ 0.99240976,  1.01149463,  1.00314781, ...,  0.99184279,
        -0.62115074,  0.41464953],
       ...,
       [-1.00764829, -0.98863599,  1.00314781, ...,  0.99184279,
         0.75645968,  1.07866125],
       [ 0.99240976,  1.01149463, -0.99686207, ..., -1.00822429,
        -1.0011812 , -1.26285378],
       [-1.00764829, -0.98863599,  1.00314781, ..., -1.00822429,
         0.37642922, -0.2493622 ]])

### logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
Logi_Regression = LogisticRegression()

In [24]:
Logi_Regression.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
y_pred_logi_train = Logi_Regression.predict(X_train)
y_pred_logi = Logi_Regression.predict(X_test)
y_pred_logi

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [26]:
accuracy_logistic_regression_without_std = accuracy_score(y_test,y_pred_logi)
print("Prediction Accuracy By Logistic Regration without standard scaler : ",accuracy_logistic_regression_without_std)
accuracy_logistic_regression_without_std_train = accuracy_score(y_train,y_pred_logi_train)
print("Prediction Accuracy By Logistic Regration without standard scaler for train : ",accuracy_logistic_regression_without_std_train)

Prediction Accuracy By Logistic Regration without standard scaler :  1.0
Prediction Accuracy By Logistic Regration without standard scaler for train :  1.0


In [27]:
classify_report_logi_without_std = classification_report(y_test,y_pred_logi)
print(classify_report_logi_without_std)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



In [28]:
Logi_Regression.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [29]:
y_pred_logi = Logi_Regression.predict(X_test_std)
y_pred_logi

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [30]:
accuracy_logistic_regression = accuracy_score(y_test,y_pred_logi)
print("Predict Accuracy by Logistic Regression with Standard Scaller : ",accuracy_logistic_regression)

Predict Accuracy by Logistic Regression with Standard Scaller :  1.0


In [31]:
classify_report_logi = classification_report(y_test,y_pred_logi)
print(classify_report_logi)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



### Decision Tree Classification

In [32]:
from sklearn.tree import DecisionTreeClassifier

In [33]:
DT_model = DecisionTreeClassifier()

In [34]:
DT_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [35]:
y_pred_DT = DT_model.predict(X_test)
y_pred_DT

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [36]:
accuracy_DT_without_std = accuracy_score(y_test,y_pred_DT)
print("Prediction Accuracy By Decision Tree Classification without standard scaler : ",accuracy_DT_without_std)

Prediction Accuracy By Decision Tree Classification without standard scaler :  1.0


In [37]:
classify_report_DT_without_std = classification_report(y_test,y_pred_DT)
print(classify_report_DT_without_std)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



In [38]:
DT_model.fit(X_train_std,y_train)

DecisionTreeClassifier()

In [39]:
y_pred_DT = DT_model.predict(X_test_std)
y_pred_DT

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [40]:
accuracy_DT = accuracy_score(y_test,y_pred_DT)
print("Prediction Accuracy By Decision Tree Classification with standard scaler : ",accuracy_DT)

Prediction Accuracy By Decision Tree Classification with standard scaler :  1.0


In [41]:
classify_report_DT = classification_report(y_test,y_pred_DT)
print(classify_report_DT)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



### Random Forest Classification

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
RF_model = RandomForestClassifier(n_estimators=50,random_state=0)

In [44]:
RF_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(n_estimators=50, random_state=0)

In [45]:
y_pred_RF = RF_model.predict(X_test)
y_pred_RF

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [46]:
accuracy_RF_without_std = accuracy_score(y_test,y_pred_RF)
print("Prediction Accuracy By Random Forest Classification without standard scaler : ",accuracy_RF_without_std)

Prediction Accuracy By Random Forest Classification without standard scaler :  1.0


In [47]:
classify_report_RF_without_std = classification_report(y_test,y_pred_RF)
print(classify_report_RF_without_std)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



In [48]:
RF_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(n_estimators=50, random_state=0)

In [49]:
y_pred_RF = RF_model.predict(X_test_std)
y_pred_RF

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [50]:
accuracy_RF = accuracy_score(y_test,y_pred_RF)
print("Prediction Accuracy By Random Forest Classification with standard scaler : ",accuracy_RF)

Prediction Accuracy By Random Forest Classification with standard scaler :  1.0


In [51]:
classify_report_RF = classification_report(y_test,y_pred_RF)
print(classify_report_RF)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



### K Nearest Neighbour Classification

In [52]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
KNN_model = KNeighborsClassifier()

In [54]:
KNN_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [55]:
y_pred_KNN = KNN_model.predict(X_test_std)
y_pred_KNN

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [56]:
accuracy_KNN = accuracy_score(y_test,y_pred_KNN)
print("Prediction Accuracy By KNearestNeighbour Classification : ",accuracy_KNN)

Prediction Accuracy By KNearestNeighbour Classification :  0.9314285714285714


In [57]:
classify_report_KNN = classification_report(y_test,y_pred_KNN)
print(classify_report_KNN)

              precision    recall  f1-score   support

           0       0.91      0.89      0.90      7306
           1       0.94      0.95      0.95     13694

    accuracy                           0.93     21000
   macro avg       0.93      0.92      0.92     21000
weighted avg       0.93      0.93      0.93     21000



### Suport Vector Classification

In [58]:
from sklearn.svm import SVC

In [59]:
SVC_model = SVC(kernel='rbf')

In [60]:
SVC_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [61]:
y_pred_svc = SVC_model.predict(X_test)
y_pred_svc

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [62]:
accuracy_svc_without_std = accuracy_score(y_test,y_pred_svc)
print("Prediction Accuracy By Suport Vector Classification without standard scaller : ",accuracy_svc_without_std)

Prediction Accuracy By Suport Vector Classification without standard scaller :  0.9994761904761905


In [63]:
classify_report_svc_without_std = classification_report(y_test,y_pred_svc)
print(classify_report_svc_without_std)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



In [64]:
SVC_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [65]:
y_pred_svc = SVC_model.predict(X_test_std)
y_pred_svc

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [66]:
accuracy_svc = accuracy_score(y_test,y_pred_svc)
print("Prediction Accuracy By Suport Vector Classification with standard scaler : ",accuracy_svc)

Prediction Accuracy By Suport Vector Classification with standard scaler :  0.9926190476190476


In [67]:
classify_report_svc = classification_report(y_test,y_pred_svc)
print(classify_report_svc)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7306
           1       0.99      0.99      0.99     13694

    accuracy                           0.99     21000
   macro avg       0.99      0.99      0.99     21000
weighted avg       0.99      0.99      0.99     21000



### Naive Bayes Classification

In [68]:
from sklearn.naive_bayes import GaussianNB

In [69]:
NB_model = GaussianNB()

In [70]:
NB_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [71]:
y_pred_nb = NB_model.predict(X_test)
y_pred_nb

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [72]:
accuracy_nb_without_std = accuracy_score(y_test,y_pred_nb)
print("Prediction Accuracy By Naive Bayes Classification without standard scaller : ",accuracy_nb_without_std)

Prediction Accuracy By Naive Bayes Classification without standard scaller :  0.9652857142857143


In [73]:
classify_report_nb_without_std = classification_report(y_test,y_pred_nb)
print(classify_report_nb_without_std)

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      7306
           1       0.98      0.96      0.97     13694

    accuracy                           0.97     21000
   macro avg       0.96      0.97      0.96     21000
weighted avg       0.97      0.97      0.97     21000



In [74]:
NB_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [75]:
y_pred_nb = NB_model.predict(X_test_std)
y_pred_nb

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [76]:
accuracy_nb = accuracy_score(y_test,y_pred_nb)
print("Prediction Accuracy By Naive Bayes Classification with standard scaler : ",accuracy_nb)

Prediction Accuracy By Naive Bayes Classification with standard scaler :  0.965047619047619


In [77]:
classify_report_nb = classification_report(y_test,y_pred_nb)
print(classify_report_nb)

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      7306
           1       0.98      0.96      0.97     13694

    accuracy                           0.97     21000
   macro avg       0.96      0.97      0.96     21000
weighted avg       0.97      0.97      0.97     21000



### Baggin Classifier

In [78]:
from sklearn.ensemble import BaggingClassifier , RandomForestClassifier

In [79]:
Baggin_model = BaggingClassifier(base_estimator=RandomForestClassifier(),n_estimators=5)

In [80]:
Baggin_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=RandomForestClassifier(), n_estimators=5)

In [81]:
y_pred_bagging_rf = Baggin_model.predict(X_test)
y_pred_bagging_rf

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [82]:
accuracy_bagging_rf_without_std = accuracy_score(y_test,y_pred_bagging_rf)
print("Prediction Accuracy By Baggin by rf Classification with standard scaler : ",accuracy_bagging_rf_without_std)

Prediction Accuracy By Baggin by rf Classification with standard scaler :  1.0


In [83]:
classify_report_bagging_rf_without_std = classification_report(y_test,y_pred_bagging_rf)
print(classify_report_bagging_rf_without_std)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



In [84]:
Baggin_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\ensemble\_bagging.py:802: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=RandomForestClassifier(), n_estimators=5)

In [85]:
y_pred_bagging_rf = Baggin_model.predict(X_test_std)
y_pred_bagging_rf

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [86]:
accuracy_bagging_rf = accuracy_score(y_test,y_pred_bagging_rf)
print("Prediction Accuracy By Baggin by rf Classification with standard scaler : ",accuracy_bagging_rf)

Prediction Accuracy By Baggin by rf Classification with standard scaler :  1.0


In [87]:
classify_report_bagging_rf = classification_report(y_test,y_pred_bagging_rf)
print(classify_report_bagging_rf)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



### AdaBoost Classification

In [88]:
from sklearn.ensemble import AdaBoostClassifier

In [89]:
Ada_model = AdaBoostClassifier(n_estimators=10,random_state=0)

In [90]:
Ada_model.fit(X_train,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(n_estimators=10, random_state=0)

In [91]:
y_pred_Ada = Ada_model.predict(X_test)
y_pred_Ada

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [92]:
accuracy_Ada_without_std = accuracy_score(y_test,y_pred_Ada)
print("Prediction Accuracy By AdaBoost  Classification without standard scaler : ",accuracy_Ada_without_std)

Prediction Accuracy By AdaBoost  Classification without standard scaler :  1.0


In [93]:
classify_report_Ada_without_std = classification_report(y_test,y_pred_Ada)
print(classify_report_Ada_without_std)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



In [94]:
Ada_model.fit(X_train_std,y_train)

C:\Users\Krish\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(n_estimators=10, random_state=0)

In [95]:
y_pred_Ada = Ada_model.predict(X_test_std)
y_pred_Ada

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [96]:
accuracy_Ada = accuracy_score(y_test,y_pred_Ada)
print("Prediction Accuracy by Adaboost Classification with Standard Scaler : ",accuracy_Ada)

Prediction Accuracy by Adaboost Classification with Standard Scaler :  1.0


In [97]:
classify_report_Ada = classification_report(y_test,y_pred_Ada)
print(classify_report_Ada)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000



### Cross-Validation with KFold For classification

In [98]:
from sklearn.model_selection import KFold

In [99]:
KF_model = KFold(n_splits=3,shuffle=True,random_state=0)
model = DecisionTreeClassifier()

In [100]:
fold = 1
sc = StandardScaler()
X = np.array(x)
Y = np.array(y)
for train_index, test_index in KF_model.split(X):
    print(f"Fold {fold} accuracy without std : ")
    X_train,X_test = X[train_index] , X[test_index]
    y_train,y_test = Y[train_index] , Y[test_index]
    
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    accuracy_KF_fold = accuracy_score(y_test,y_pred)
    print(accuracy_KF_fold)
    print(classification_report(y_test,y_pred))
    print('----------------------')
    fold += 1

Fold 1 accuracy without std : 
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8114
           1       1.00      1.00      1.00     15220

    accuracy                           1.00     23334
   macro avg       1.00      1.00      1.00     23334
weighted avg       1.00      1.00      1.00     23334

----------------------
Fold 2 accuracy without std : 
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8284
           1       1.00      1.00      1.00     15049

    accuracy                           1.00     23333
   macro avg       1.00      1.00      1.00     23333
weighted avg       1.00      1.00      1.00     23333

----------------------
Fold 3 accuracy without std : 
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      8158
           1       1.00      1.00      1.00     15175

    accuracy                   

### Accuracy Results

In [101]:
#Logistic Regression
print("Logistic Regression")
print(f"Accuracy_without_std : {accuracy_logistic_regression_without_std} , Accuracy_with_std : {accuracy_logistic_regression}")
print("\n classification_report_without_std")
print(classify_report_logi_without_std)
print("\n classification_report_with_std")
print(classify_report_logi)

print('------------------------------------------------------------------------------------------')

#Decision Tree
print('Decision Tree')
print(f"Accuracy_without_std : {accuracy_DT_without_std} , Accuracy_with_std : {accuracy_DT}")
print("\n classification_report_without_std")
print(classify_report_DT_without_std)
print("\n classification_report_with_std")
print(classify_report_DT)

print('------------------------------------------------------------------------------------------')

#Random Forest
print('Random Forest')
print(f"Accuracy_without_std : {accuracy_RF_without_std} , Accuracy_with_std : {accuracy_RF}")
print("\n classification_report_without_std")
print(classify_report_RF_without_std)
print("\n classification_report_with_std")
print(classify_report_RF)

print('------------------------------------------------------------------------------------------')

#K Nearest Neighbour
print('K Nearest Neighbour')
print(f"Accuracy_with_std : {accuracy_KNN}")
print("\n classification_report_with_std")
print(classify_report_KNN)

print('------------------------------------------------------------------------------------------')

#Support Vector Classifier
print('Support Vector Classifier')
print(f"Accuracy_without_std : {accuracy_svc_without_std} , Accuracy_with_std : {accuracy_svc}")
print("\n classification_report_without_std")
print(classify_report_svc_without_std)
print("\n classification_report_with_std")
print(classify_report_svc)

print('------------------------------------------------------------------------------------------')

#Naive Bayes Classification
print('Naive Bayes Classification')
print(f"Accuracy_without_std : {accuracy_nb_without_std} , Accuracy_with_std : {accuracy_nb}")
print("\n classification_report_without_std")
print(classify_report_nb_without_std)
print("\n classification_report_with_std")
print(classify_report_nb)

print('------------------------------------------------------------------------------------------')

#Bagging using RF Classification
print('Bagging using RF Classification')
print(f"Accuracy_without_std : {accuracy_bagging_rf_without_std} , Accuracy_with_std : {accuracy_bagging_rf}")
print("\n classification_report_without_std")
print(classify_report_bagging_rf_without_std)
print("\n classification_report_with_std")
print(classify_report_bagging_rf)

print('------------------------------------------------------------------------------------------')

#AdaBoost Classification
print('AdaBoost Classification')
print(f"Accuracy_without_std : {accuracy_Ada_without_std} , Accuracy_with_std : {accuracy_Ada}")
print("\n classification_report_without_std")
print(classify_report_Ada_without_std)
print("\n classification_report_with_std")
print(classify_report_Ada)

Logistic Regression
Accuracy_without_std : 1.0 , Accuracy_with_std : 1.0

 classification_report_without_std
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000


 classification_report_with_std
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7306
           1       1.00      1.00      1.00     13694

    accuracy                           1.00     21000
   macro avg       1.00      1.00      1.00     21000
weighted avg       1.00      1.00      1.00     21000

------------------------------------------------------------------------------------------
Decision Tree
Accuracy_without_std : 1.0 , Accuracy_with_std : 1.0

 classification_report_without_std
          